name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x', '6.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Run
      run: dotnet run --project ConsoleApp/ConsoleApp/ConsoleApp.csproj
    - name: Test
      run: dotnet test wasmtime-dotnet/tests/Wasmtime.Tests.csproj -v diag --blame-crash
